name: "FRC West"
description: "FRC (FIRST Robotics Competition) in Western Canada"

permalink: pretty
url: http://frcwest.com

paginator: 5

markdown: rdiscount

exclude: [send.sh]

ftp_host: 64.34.157.160
ftp_dir: /
ftp_passive: false
